/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectoagileeder;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;

/**
 *
 * @author IGNACIO
 */
public class PantallaEditarPasajeros extends javax.swing.JFrame {

    /**
     * Creates new form PantallaEditarPasajeros
     */
    public PantallaEditarPasajeros() {  
        initComponents();
        setTitle("Editar Cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfCiudad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfProvincia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfNumTelefono = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("DNI:");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Ciudad:");

        jLabel6.setText("Provincia:");

        jLabel7.setText("Telefono:");

        btnAceptar.setText("Aceptar");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfApellido)
                            .addComponent(jtfNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDocumento)
                            .addComponent(jtfNumTelefono)
                            .addComponent(jtfProvincia)
                            .addComponent(jtfCiudad)
                            .addComponent(jtfDireccion))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaEditarPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaEditarPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaEditarPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaEditarPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaEditarPasajeros().setVisible(true);
            }
        });
    }
    
    private class ManejadorNombre extends KeyAdapter{
        @Override
        public void keyPressed(KeyEvent e){
            if(e.getKeyCode()==10){
                if(jtfNombre.getText().length()>0){
                    jtfNombre.setBackground(Color.GREEN);
                    jtfApellido.requestFocusInWindow();
                }else{
                    jtfNombre.setBackground(Color.RED);
                }
            }
        }
        
        @Override
        public void keyTyped(KeyEvent e){
            if(Character.isLetter(e.getKeyChar())){               
            }else{
                e.setKeyCode(Character.MIN_VALUE);
                e.consume();
            }
        }
    }
    
    private class ManejadorApellido extends KeyAdapter{
        @Override
        public void keyPressed(KeyEvent e){
            if(e.getKeyCode()==10){
                if(jtfApellido.getText().length()>0){
                    jtfApellido.setBackground(Color.GREEN);
                    jtfDocumento.requestFocusInWindow();
                }else{
                    jtfApellido.setBackground(Color.RED);
                }
            }
        }
        
        @Override
        public void keyTyped(KeyEvent e){
            if(Character.isLetter(e.getKeyChar())){               
            }else{
                e.setKeyCode(Character.MIN_VALUE);
                e.consume();
            }
        }
    }
    
    private class ManejadorDocumento extends KeyAdapter{
        
        @Override
        public void keyPressed(KeyEvent e){
            if(e.getKeyCode()==10){
                if(jtfDocumento.getText().length()>0 && jtfDocumento.getText().length()<9){
                    jtfDocumento.setBackground(Color.GREEN);
                    jtfDireccion.requestFocusInWindow();
                }else{
                    jtfDocumento.setBackground(Color.RED);
                }
            }
        }
        
        @Override
        public void keyTyped(KeyEvent e){
            if (Character.isDigit(e.getKeyChar())) {
            } else {
                e.setKeyCode(Character.MIN_VALUE);
                e.consume();
            }
        }
    }
    
    private class ManejadorDireccion extends KeyAdapter{
        @Override
        public void keyPressed(KeyEvent e){
            if(e.getKeyCode()==10){
                if(jtfDireccion.getText().length()>0){
                    jtfDireccion.setBackground(Color.GREEN);
                    jtfNumTelefono.requestFocusInWindow();
                }else{
                    jtfDireccion.setBackground(Color.RED);
                }
            }
        }
        
        @Override
        public void keyTyped(KeyEvent e){
            if(Character.isLetter(e.getKeyChar()) || Character.isDigit(e.getKeyChar()) || Character.isSpaceChar(e.getKeyChar())){
            }else{
                e.setKeyCode(Character.MIN_VALUE);
                e.consume();
            }
        }
    }
    
    private class ManejadorTelefono extends KeyAdapter{
        
        @Override
        public void keyPressed(KeyEvent e){
            if(e.getKeyCode()==10){
                if(jtfNumTelefono.getText().length()>0){
                    jtfNumTelefono.setBackground(Color.GREEN);
                    btnAceptar.setEnabled(true);
                    btnAceptar.requestFocusInWindow();
                }else{
                    jtfNumTelefono.setBackground(Color.RED);
                }
            }
        }
        
        @Override
        public void keyTyped(KeyEvent e){
            if(Character.isDigit(e.getKeyChar()) || Character.compare('-', e.getKeyChar())==0){
                
            }else{
                e.setKeyCode(Character.MIN_VALUE);
                e.consume();
            }
        }
    }
//    
//    private class ManejadorEmail extends KeyAdapter{
//        @Override
//        public void keyPressed(KeyEvent e){
//            if(e.getKeyCode()==10){
//                if(jtfEmail.getText().length()>0){
//                    jtfEmail.setBackground(Color.GREEN);
//                    botonAceptar.setEnabled(true);
//                    botonAceptar.requestFocusInWindow();
//                }else{
//                    jtfEmail.setBackground(Color.RED);
//                }
//            }
//        }
//        
//        @Override
//        public void keyTyped(KeyEvent e){
//            if(Character.isLetter(e.getKeyChar()) || Character.isDigit(e.getKeyChar()) || Character.compare('_', e.getKeyChar())==0 || Character.compare('.', e.getKeyChar())==0 || Character.compare('@', e.getKeyChar())==0){
//                
//            }else{
//                e.setKeyCode(Character.MIN_VALUE);
//                e.consume();
//            }
//        }
//    }
    
    private class ManejadorCiudad extends KeyAdapter{
        @Override
        public void keyPressed(KeyEvent e){
            if(e.getKeyCode()==10){
                if(jtfCiudad.getText().length()>0){
                    jtfCiudad.setBackground(Color.GREEN);
                    jtfProvincia.requestFocusInWindow();
                }else{
                    jtfCiudad.setBackground(Color.RED);
                }
            }
        }
        
        @Override
        public void keyTyped(KeyEvent e){
            if(Character.isLetter(e.getKeyChar())){               
            }else{
                e.setKeyCode(Character.MIN_VALUE);
                e.consume();
            }
        }
    }
    
        private class ManejadorProvincia extends KeyAdapter{
        @Override
        public void keyPressed(KeyEvent e){
            if(e.getKeyCode()==10){
                if(jtfProvincia.getText().length()>0){
                    jtfProvincia.setBackground(Color.GREEN);
                    jtfNumTelefono.requestFocusInWindow();
                }else{
                    jtfProvincia.setBackground(Color.RED);
                }
            }
        }
        
        @Override
        public void keyTyped(KeyEvent e){
            if(Character.isLetter(e.getKeyChar())){               
            }else{
                e.setKeyCode(Character.MIN_VALUE);
                e.consume();
            }
        }
    }
    
    private class ManejadorBoton implements ActionListener{
        private JFrame ventana;
        public ManejadorBoton(JFrame ventana){
            this.ventana=ventana;
        }
        @Override
        public void actionPerformed(ActionEvent e) {
           ventana.dispose();
        }
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfCiudad;
    private javax.swing.JTextField jtfDireccion;
    private javax.swing.JTextField jtfDocumento;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNumTelefono;
    private javax.swing.JTextField jtfProvincia;
    // End of variables declaration//GEN-END:variables
}
